name: openspent_website
description: OpenSpent static landing page.
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: "3.11.5"

dependencies:
  jaspr: 0.23.5
  jaspr_hooks: 0.2.0

dev_dependencies:
  jaspr_test: 0.23.5
  lints: 6.0.0
  test: 1.30.0

jaspr:
  mode: static
  port: 8081
